# Site settings
name: aprilandjan
title:       aprilandjan's blog
email:       youremail@example.com
author:      aprilandjan
description: ""
baseurl:     ""
url:         "/"

#Duoshuo short Name / 多说的shortname
duoshuo:

#Baidu analytics / 百度统计(异步的js码，注意使用异步版本的)
baidu_analyze:

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: false
github_username:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     5
sass:
  compressed: true

# Gems
gems: [jekyll-paginate]

# dev
port: 4321